### PR TITLE
Add Data.Monoid.Alternate from prelude v3.3.0

### LINKED ISSUE #9: Consider adding `control` dependency and `Alternate` instance
See discussion in https://github.com/purescript/purescript-prelude/issues/179

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #9

### CODE REVIEW

**Review by hdgarrood — APPROVED** [review]

**Comment by hdgarrood** [comment]
CI is failing because we need to update `control` first.

**Comment by JordanMartinez** [comment]
Note: the `control` PR CI is failing because `newtype` hasn't been updated yet. Moreover, `newtype`'s PR (purescript/purescript-newtype#23) can be merged, but might need to be adjusted later depending on whether we merge something in the `purescript` compiler repo.

**Comment by JordanMartinez** [comment]
I think CI will pass now if we restart it

**Comment by hdgarrood** [comment]
:+1: I've just restarted the build. Just so you know, I think that if you sign in with github on travis-ci.org, you'll be able to restart builds too.

**Comment by JordanMartinez** [comment]
The only repo that shows up on travis-ci.org for me is `spago`.

CI is now failing with this error. I'll look into it as this PR was submitted using my `spago`-based approach:
```
* Building project in /home/travis/build/purescript/purescript-invariant

[1/1 TypesDoNotUnify] src/Data/Functor/Invariant.purs:51:41

  51    imap f _ (Alternate x) = Alternate (f x)

                                              ^

  

  Could not match type

  

    f3 a0

  

  with type

  

    a0

  

  while checking that type t1 t2

    is at least as general as type a0

  while checking that expression x

    has type a0

  in value declaration invariantAlternate

  

  where f3 is a rigid type variable

          bound at (line 0, column 0 - line 0, column 0)

        a0 is a rigid type variable

          bound at (line 0, column 0 - line 0, column 0)

        t1 is an unknown type

        t2 is an unknown type

           Src   Lib   All

Warnings   0     0     0  

Errors     1     0     1  

* ERROR: Subcommand terminated with exit code 1

The command "npm run -s build" exited with 1.
cache.2

store build cache
```

**Review by hdgarrood — APPROVED** [review]

**Pull request merged**
